shinyUI(pageWithSidebar(  
  headerPanel("Audit selector tool"),  
  sidebarPanel(    
    sliderInput('Age', 'Enter age', value = 37, min = 17, max = 83, step = 1),
    selectInput('Employment', 'Enter employment', choices = c("Consultant" = "Consultant",
                                                              "Private" = "Private",
                                                              "Public Servant - Federal"= "PSFederal",
                                                              "Public Servant - Local" = "PSLocal", 
                                                              "Public Servant - State" = "PSState", 
                                                              "Self Employed" = "SelfEmp", 
                                                              "Volunteer" = "Volunteer")),
    selectInput('Education', 'Enter highest education achieved', choices = c("Associate",
                                                                             "Bachelor",
                                                                             "College",
                                                                             "Doctorate",
                                                                             "High School" = "HSgrad",
                                                                             "Master",
                                                                             "Preschool",
                                                                             "Professional",
                                                                             "Vocational",
                                                                             "Year 10" = "Yr10",
                                                                             "Year 11" = "Yr11",
                                                                             "Year 12" = "Yr12",
                                                                             "Year 1 to 4" = "Yr1t4",
                                                                             "Year 5 to 6" = "Yr5t6",
                                                                             "Year 7 to 8" = "Yr7t8",
                                                                             "Year 9" = "Yr9"),
                selected = "Bachelor"),
    selectInput('Marital', 'Enter marital status', choices = c("Absent",
                                                               "Divorced",
                                                               "Married",
                                                               "Married - Spouse absent" = "Married-spouse-absent",
                                                               "Unmarried", 
                                                               "Widowed"),
                selected = "Married"),
    selectInput('Occupation', 'Enter occupation', choices = c("Cleaner",
                                                              "Clerical",
                                                              "Executive",
                                                              "Farming",
                                                              "Home", 
                                                              "Machinist",
                                                              "Military",
                                                              "Professional",
                                                              "Protective",
                                                              "Repair", 
                                                              "Sales",
                                                              "Service",
                                                              "Support",
                                                              "Technical")),
    sliderInput('Income', 'Enter income', value = 100000, min = 610, max = 481260, step = 5000),
    selectInput('Gender', 'Enter Gender', choices = c("Female", "Male")),
    sliderInput('Deductions', 'Enter deductions', value = 100, min = 0, max = 2513, step = 100)),
  mainPanel(
    h3('Result of audit selector tool:'),
    h2(textOutput("Prediction")),
    h3('Graphs of previous audit outcomes:'),
    plotOutput("AgePlot")
    )
))